development:
  clients:
    default:
      database: ruby_moon_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: ruby_moon_test
      hosts:
        - localhost:27017
      options:
        max_pool_size: 1

production:
  clients:
    default:
      database: ruby_moon_production
      hosts:
        - localhost:27017